jobs:
  test:
    requires: [ ~pr, ~commit ]
    image: node:8
    steps:
      - init: npm install
      - test: npm test
      - meta_set: meta set gopher dojo
  meta_get:
    requires: [ test ]
    image: golang:latest
    steps:
      - meta_get: meta get gopher
